apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: kubernetes.io/basic-auth
stringData:
  username: bWlzc2F3ZXNvbWU= # required field for kubernetes.io/basic-auth
  password: MTIza3ViZTMx # required field for kubernetes.io/basic-auth



